__title__ = 'dfsql'
__package_name__ = 'dfsql'
__version__ = '0.4.2'
__description__ = "SQL interface to Pandas"
__email__ = "jorge@mindsdb.com"
__author__ = 'MindsDB Inc'
__github__ = 'https://github.com/mindsdb/dfsql'
__pypi__ = 'https://pypi.org/project/dfsql'
__license__ = 'GPL-3.0'
__copyright__ = 'Copyright 2020- mindsdb'
